spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: cgbYwWuROygbJZOusLBazckioiUDrRGp
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop