spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sd2024
    username: root
    password: VgVFT2@2@$CCP1910
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate # validate | update | create | create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

